sudo: required
services:
  - docker

before_install:
  - docker build -t olasupoodebiyi/docker-react -f Dockerfile.dev .

script:
  - docker run olasupoodebiyi/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "Docker React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-869461107721"
  bucket_path: "Docker React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
